### ISSUE TITLE
[SCRIPT REQUEST] : [Sorting latitudes and longitudes]

### ISSUE THREAD

**Issue by rkulranjan** [atreebangalore/ruralwaterLayers#22]
**READ THIS FIRST**
file a script request ONLY if your problem meets these three criteria
1) The problem is a recurring one
2) A solution isn't required urgently
3) It is in fact a single problem, not a multi-stage problem

**Is your script request related to a problem? Please describe. (1-2 sentences)**
This is a task I have to do manually.

**Describe the INPUT FORMAT/FILES to solve the problem**
The file contains data on water quality of different parameters with the location of the wells. The information is at India level. The file has been added to the link below:
(https://drive.google.com/drive/folders/1LVX-_JfPBd2sQnNoHTipmqf6H2Jwwq3e) 

**Describe the PROCESSING/INTERMEDIARY STEPS needed**
The columns 'Latitude' and 'Longitude' contains values in different formats i.e., degree decimal and degree minutes seconds. This can't be read by the GIS software directly. 

**Describe the OUTPUT FORMAT you'd like to see**
The column's latitude and longitude need to be brought into a single format of degree decimals. 

**Describe alternatives you've considered (OPTIONAL)**
I cleaned up the data manually on excel. The steps are as follows
1. Add Blank columns 
2. Copy the data from the 'Latitude' column
3. Keep only cells that contain the values that need to be corrected (degree minutes seconds). 
4. Using the text to column option separate out the degree, minutes, and seconds values.
5. Use the conversion formula and add up all the columns to get the final value in degrees decimal.

**Additional context**

**Comment by balakumaran247** [comment]
@rkulranjan what to do in case of uninterpretable values?
23° 04.070´
