### ISSUE TITLE
[IMPLEMENTATION REQUEST]: Build Groundwater Levels dataset

### ISSUE THREAD

**Issue by craigdsouza** [atreebangalore/ruralwaterLayers#26]
## Please describe the task in 1-2 sentences below
Download groundwater levels data (xls) from India WRIS website and merge these files together.
Then compare this dataset to the original levels dataset, obtained from Tejasvi (for 1996-2016)
Begin with test case of Karnataka for Dec 1993 till May 1998

## List links to the ruralwaterlayers scripts OR external websites required for the above task
https://indiawris.gov.in/wris/#/DataDownload
https://github.com/atreebangalore/ruralwaterLayers/blob/master/scripts/groundwater/levels/0_gw_preparation.py

## Report results in this format (implementation/testing)
**test case**
- [x]  single csv file with columns showing data for 5 years 
- [x]  1993-94 (All India)
- [x]  ...
- [x] 2020-21 (All India)

**Comment by jaltol** [comment]
Hi there! 1993 has only December data which is null. The year 1994 to 1995 shows no data and from 1996 to 99 only a few month has data and others are '-' (null)

**Comment by craigdsouza** [comment]
Then download from 1996 to 99 for the test case.

**Comment by jaltol** [comment]
> Then download from 1996 to 99 for the test case.

Sure will do that

**Comment by jaltol** [comment]
(Arundhati) The output file CGWB_data has data only for the year 1996, even though 97, 98, 99 does have data present in the downloaded Indiawris xls files.

**Comment by balakumaran247** [comment]
place one year file at a time in the downloaded_cgwb folder and try running.

**Comment by jaltol** [comment]
![image](https://user-images.githubusercontent.com/94048268/178207061-3ba4fd0c-cba7-4b99-84d3-c37a76ea9f52.png)

(Arundhati) Hi I'm attaching this error when I try running the same script for Andhra Pradesh.

**Comment by balakumaran247** [comment]
ValueError: could not convert string to float: '-'
resolved by replacing with np.nan (commit: d885270)

**Comment by balakumaran247** [comment]
KeyError: "None of [Index(['LON', 'LAT'], dtype='object')] are in the [columns]"
resolved by removing whitespaces in Latitude and Longitude column headings (commit: c0cdd5c)

**Comment by balakumaran247** [comment]
To update your local file with latest GitHub Repository, in Git Bash do:

cd Code\atree
git pull

**Comment by balakumaran247** [comment]
Arundhati, test merging Maharashtra files to the existing one with Karnataka datas and check for one month of three different years both for Karnataka values and Maharashtra values from the downloaded xls to the merged csv. After making sure that all data for the month in downloaded file is merged successfully with the output, you can continue for other states.

India-WRIS GW Download STATUS:
Arundhati, I have provided a link below for a google sheet, as you download xls files from India-WRIS for different states, different years, please put a 'Y' in the sheet if you have downloaded the xls (even if all data is '-' for all months) for a state for downloaded year and put 'N' if you were not able to download or the downloaded file is blank as in Tamil Nadu files.
https://docs.google.com/spreadsheets/d/14JflY9v5k76keCg0SM3wHp3PBuX1QfDfs0u2H1xRA8U/edit?usp=sharing

Downloaded Files:
I have provided a link for a GDrive Folder where you can put the downloaded xls files organized by year (year as folder names) for all the states.
https://drive.google.com/drive/folders/1U-tofy1i_sIzEourr8y1XTQIdGnT9KMN?usp=sharing

**Comment by arundhatid99** [comment]
I'm trying to merge the csv file with Maharashtra data but the csv got updated with nothing, without any error in the script.
![Screenshot 2022-07-21 233045](https://user-images.githubusercontent.com/97686266/180282579-2c56e472-5f31-4f62-a561-2c10de7104e3.jpg)

**Comment by balakumaran247** [comment]
Fixed the issue.

**Comment by jaltol** [comment]
Script works fine now.

**Comment by jaltol** [comment]
@balakumaran247 Attaching the screenshot of the error while trying to merge the downloaded xls files for Andhra Pradesh with existing csv.
![Screenshot 2022-07-24 160638](https://user-images.githubusercontent.com/94048268/180643340-414a9b93-4268-444a-a842-c2780abba19f.jpg)

**Comment by balakumaran247** [comment]
PermissionError occurs when you run the script with the csv opened in Excel.

**Comment by jaltol** [comment]
Reporting this issue when merging the downloaded xls files for Arunachal Pradesh 1994 @balakumaran247 

![Screenshot 2022-07-25 160650](https://user-images.githubusercontent.com/94048268/180758038-078af202-739e-422d-9e1b-b1b0da319e9f.jpg)

**Comment by balakumaran247** [comment]
Try now.

**Comment by arundhatid99** [comment]
Same error is popping up even when tried with other state.

**Comment by balakumaran247** [comment]
commit 1e45526 - tried to fix InvalidIndexError: uniquely valued Index objects, added lines to remove duplicate index values in both conc and df

commit e1a8756 - tried to fix a logical error (script runs fine but the output won't be intended one), sometimes meta columns like LAT, LON, STATE, STATION TYPE values will get erased in the output, to rectify this, new function called computation will split the concatenated DataFrame into metacolumn DataFrame and Monthly Data DataFrame, computation, merging and cleaning happens to both the DataFrame and returns the merged DataFrame.

**Comment by balakumaran247** [comment]
Please check the merged csv after each run.

**Comment by arundhatid99** [comment]
The script is working fine now.

**Comment by jaltol** [comment]
Station and Station type is getting changed in the csv, ex. station KWD-027-OW from the downloaded Chhattisgarh xls changing to KWD alone in csv and station type '-' is being converted to nan.

![Screenshot 2022-07-27 155236](https://user-images.githubusercontent.com/94048268/181224686-2b9ba3fa-213b-4a9f-9e99-ca13481babf1.jpg)

![image](https://user-images.githubusercontent.com/94048268/181225867-603f018f-1911-4530-b062-4184b4dec54b.png)

**Comment by balakumaran247** [comment]
commit 5939beb - fixed the above, changed the placeholder.

**Comment by jaltol** [comment]
Reporting new issue when running for Delhi year 1995 xls file ValueError: could not convert string to float:

![Screenshot 2022-07-27 175820](https://user-images.githubusercontent.com/94048268/181246717-0d3693b3-7d77-4fbd-a49d-71d4dee4b6e0.jpg)

**Comment by jaltol** [comment]
KeyError: '28.684444440247773,77.25972221996783' while trying to merge Delhi 1997 to csv.

![Screenshot 2022-07-27 191000](https://user-images.githubusercontent.com/94048268/181261507-1399d666-5ef8-4eef-9f5b-239af7c3725f.jpg)

**Comment by balakumaran247** [comment]
commit 98a3a19 - changed Data Cols Column headings so as to prevent errors like having both 'Aug-96' and 'Aug 1996' in same file, drop empty columns.

commit 4f84b85 - updated 1_gw_preProcess and 4_gw_rasterize

**Comment by jaltol** [comment]
Reporting issue when kept all the state xls files in a single folder and running the script.
KeyError: '16.1833333, 74.983333'

![unnamed](https://user-images.githubusercontent.com/94048268/182308216-1053967f-af06-4cda-b658-4eb189ce11d2.png)

**Comment by balakumaran247** [comment]
commit 7ff2f94 - resolved keyerror

**Comment by jaltol** [comment]
New issue when merging downloaded xls Meghalaya 1994.

![Screenshot 2022-08-08 203324](https://user-images.githubusercontent.com/94048268/183449584-5f54f8de-8967-40e5-8e44-541d803f3e8d.jpg)

**Comment by arundhatid99** [comment]
Reporting a new issue: the values are getting changed when merging the xls

**Comment by balakumaran247** [comment]
commit 95b9f14 - fixed value changing after merge.

**Comment by jaltol** [comment]
Yes, started rerunning the script.

**Comment by jaltol** [comment]
Reporting new issue while uploading groundwater (year 1996) tif files to Google Earth Engine from GCP bucket.

![GW_GEEupload_error](https://user-images.githubusercontent.com/94048268/185410099-562cfc9e-3438-4c62-abcc-f8c5f482d2f4.jpg)

**Comment by jaltol** [comment]
![gee](https://user-images.githubusercontent.com/94048268/186223067-a78e0daa-462c-43f0-aae9-48cd54a06b24.jpg)

(GCP to GEE script Error: Input has missing or invalid affine transform. (Error code: 3) Reporting issue for a the files from year 1996 (months 02, 06,07, 09, 10), 1999 (02), 2000 (02, 07, 09), 2001 (02, 07, 09), 2002 (02, 07, 09), 2003 (02, 06, 07)

**Comment by balakumaran247** [comment]
Groundwater data uploaded to GEE ImageCollection,
https://code.earthengine.google.co.in/?asset=users/jaltol/GW/IndiaWRIS
A few images in 1996, 1999, 2000, 2001, 2002, and 2003 could not be uploaded due to some Affine Transformation Error.
Closing the Implementation Request Issue.
