### ISSUE TITLE
[SCRIPT REQUEST] : [Rainfall data extraction for different scales]

### ISSUE THREAD

**Issue by shashankpalur** [atreebangalore/ruralwaterLayers#29]
Reference script: https://code.earthengine.google.co.in/?scriptPath=users%2Fcseicomms%2Fboundarywise_layer_stats%3Astat_all_datasets

Need a script for town/taluk level rainfall data from the gridded IMD dataset.

Output: csv file with monthly data over years.

**Comment by balakumaran247** [comment]
@shashankpalur have created a plugin for QGIS that could provide many processing tools, first tool created is Boundary wise statistics that can use any shapefile and get the stats as the earth engine script.
The tool can be downloaded from this link,
https://drive.google.com/file/d/11BYJOLVf8Pbw2Ft05fs9yrcZQjE6Ygca/view?usp=sharing

CSEI-Tools

Installing:
QGIS -> Plugins menu -> Manage and Install Plugins...
In the Plugins UI -> Install from ZIP (left side) -> "..." button (choose the zip file) -> Install Plugin

CSEI-Tools will be available in Plugins menu.
Plugins -> CSEI-Tools -> Boundary Statistics

1) Select Input Layer
Selected Features only (won't work, keep it deselected)
2) Year
3) Calendar Year - Jan to Dec
Hydrological Year - 1st June of selected year to 31st May of next year
4) Parameter - Rainfall, Tmin, Tmax or ETa
5) Temporal Step - monthly or entire year
6) Temporal Reducer - method to make the daily data into monthly or yearly
7) Spatial Reducer - method to make all pixels values available in ROI into single value
8) Unique Field - Heading of the Field in shp that has unique values
eg: if a shape file had attributes of State, District, Village data in respective StateName, DistrictName and VillageName column headings, then VillageName is the unique field.
9) Output File should be csv.

**Comment by balakumaran247** [comment]
@craigdsouza hey, if this plugin which could have many tools in it seems to be useful, we could make a repository under atreebangalore GitHub.

**Comment by balakumaran247** [comment]
hope the tool helped you, closing this issue.
